### ISSUE TITLE
rebuild_projects builda qualsiasi branch dei repository

### ISSUE THREAD

**Issue by xrmx** [italia/docs.italia.it#107]
Non so se è quello che vogliamo. E visto che ci siamo deve anche gestire meglio gli errori:

```
Traceback (most recent call last):
  File "/home/docs/docs.italia.it/readthedocs/projects/tasks.py", line 313, in run
    self.version = self.get_version(self.project, version_pk)
  File "/home/docs/docs.italia.it/readthedocs/projects/tasks.py", line 84, in get_version
    version_data = api_v2.version(version_pk).get()
  File "/home/docs/virtualenv/lib/python3.5/site-packages/slumber/__init__.py", line 155, in get
    resp = self._request("GET", params=kwargs)
  File "/home/docs/virtualenv/lib/python3.5/site-packages/slumber/__init__.py", line 101, in _request
    raise exception_class("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
slumber.exceptions.HttpNotFoundError: Client Error 404: http://localhost:8002/api/v2/version/868/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/docs/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/docs/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/docs/virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/docs/virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/docs/docs.italia.it/readthedocs/docsitalia/management/commands/rebuild_projects.py", line 33, in handle
    task.run(version.project.pk, version_pk=version.pk, build_pk=build.pk)
  File "/home/docs/docs.italia.it/readthedocs/projects/tasks.py", line 332, in run
    build_id=build_pk,
AttributeError: 'UpdateDocsTaskStep' object has no attribute 'setup_env'
```

**Comment by xrmx** [comment]
-

**Comment by xrmx** [comment]
"Linee guida di design per i servizi web della Pubblica Amministrazione" è un progetto per cui importiamo una caterva di branch

**Comment by yakky** [comment]
@francescozaia questa è ancora rilevante?

**Comment by francescozaia** [comment]
Potrebbe essere rilevante nei termini in cui va capito meglio come gestire lo script, perché ricordo ci preoccupava che potesse diventare molto pesante. Al momento abbiamo:
- alcuni documenti che hanno molti branch e dev'essere così perché hanno molte versioni online (es: [CAD](https://docs.italia.it/italia/piano-triennale-ict/codice-amministrazione-digitale-docs))
- altri documenti che hanno molti branch per motivi vari (manutenzione, storico, ecc.), ma magari solo uno pubblico

Proposte da discutere prima di chiudere la issue:
- farne una versione più "avanzata" che permetta di buildare tutti i branch per progetto o amministrazione
- impedire le build dei branch non attivi/pubblici (se non è già così)

Ne parliamo al prossimo incontro.
