### ISSUE TITLE
La compilazione delle "Linee guida del Modello di Interoperabilità" fallisce

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#168]
## Dettagli

Questo il messaggio di errore, che sembra abbastanza esplicativo:
```
Running Sphinx v1.7.4
WARNING: the config value 'settings_project_name' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u'Content'.
WARNING: the config value 'project' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u'Content'.
loading translations [it]... done
making output directory...

Traceback (most recent call last):
  File "/home/docs/docs.italia.it/user_builds/lg-modellointeroperabilita-docs/envs/bozza/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/docs.italia.it/user_builds/lg-modellointeroperabilita-docs/envs/bozza/local/lib/python2.7/site-packages/sphinx/application.py", line 227, in __init__
    self.config.check_types()
  File "/home/docs/docs.italia.it/user_builds/lg-modellointeroperabilita-docs/envs/bozza/local/lib/python2.7/site-packages/sphinx/config.py", line 204, in check_types
    default = default(self)  # could invoke l_()
  File "/home/docs/docs.italia.it/user_builds/lg-modellointeroperabilita-docs/envs/bozza/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 1428, in <lambda>
    lambda self: l_('%s %s documentation') % (self.project, self.release),
  File "/home/docs/docs.italia.it/user_builds/lg-modellointeroperabilita-docs/envs/bozza/local/lib/python2.7/site-packages/sphinx/locale/__init__.py", line 110, in __mod__
    return self.data % other
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 38: ordinal not in range(128)

Encoding error:
'ascii' codec can't decode byte 0xc3 in position 38: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-panQ9r.log, if you want to report the issue to the developers.
```
Per ora ho aggiunto @yakky tra i gestori; @paoloromolini non ho trovato un utente che apparentemente afferisse a te... fammi sapere se vuoi accesso al documento come gestore.

**Comment by francescozaia** [comment]
C'è la possibilità che questo errore sia dovuto a qualcosa di simile a https://github.com/italia/docs.italia.it/issues/138 ("InteroperabilitÀ").

**Comment by paoloromolini** [comment]
Purtroppo no

**Comment by paoloromolini** [comment]
Ho risolto così
 https://github.com/italia/lg-modellointeroperabilita-docs/commit/27d0ce4990865affd29ab2f7106201a0b9ae197e

Siccome la build di sphinx avviene  con python2.7  è necessario marcare le stringhe che contengono parole accentate o caratteri non standard come unicode.
L'alternativa sarebbe (credo) di far buildare sphinx con python 3.

Che ne pensate?

**Comment by paoloromolini** [comment]
@francescozaia anche questa potremmo chiuderla. 
Ho creato una pagina del wiki nel caso in cui dovesse ripresentarsi un problema simile:
https://github.com/italia/docs.italia.it/wiki/Problemi-nelle-build-dei-documenti

**Comment by francescozaia** [comment]
Sì, ok ragionevolissimo grazie!
