### ISSUE TITLE
Eliminazione della necessità di avere (obbligatoriamente) un file conf.py

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#265]
## Dettagli
Sarebbe utile rendere facoltativo l'uso del file conf.py.
Tutte le configurazioni potrebbero essere sostituite dal file YAML.
L'eventuale presenza del file conf.py determinerebbe un override.

Da approfondire quanto riportato su: http://docs.readthedocs.io/en/latest/yaml-config.html

**Comment by pauloxnet** [comment]
Il supporto ai file di configurazione yaml nella versione attuale di docsitalia sembra in beta.
Si può leggere tale informazione nella pagina di documentazione nel codice:
https://github.com/italia/docs.italia.it/blob/italia-2.3.13/docs/yaml-config.rst
> *Warning*
> _This feature is in a beta state. Please file an issue if you find anything wrong._

**Comment by pauloxnet** [comment]
In base quanto descritto nella guida:
https://docs.italia.it/italia/docs-italia/docs-italia-guide/it/bozza/pubblicare-un-documento.html
testare il funzionamento usando lo starter kit con file .rst e nella variante (da creare) con .md :
https://github.com/italia/docs-italia-starter-kit

**Comment by pauloxnet** [comment]
Ho verificato che già attualmente è possibile creare un progetto senza la presenza del file `conf.py`.

Ho creato un repository di documento base creato partendo dallo starter kit per pubblicare su Docs Italia:
https://github.com/comune-di-tre-civette-sul-como/tre-civette-documento

Dopo l'import del repository in locale la build si è conclusa con successo:

```bash
Build #2419
bozza (eebfaa542140bb5344d5295142d4f7c00f6f7af4)
Build completed
git clone --recursive https://github.com/comune-di-tre-civette-sul-como/tre-civette-documento.git .
git checkout --force origin/master
git clean -d -f -f
git show-ref --tags
git branch -r
python2.7 -mvirtualenv --no-site-packages --no-download /home/documents/user_builds/tre-civette-documento/envs/bozza
python /home/documents/user_builds/tre-civette-documento/envs/bozza/bin/pip install --upgrade --cache-dir /home/documents/user_builds/tre-civette-documento/.cache/pip Pygments==2.2.0 setuptools<40 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.7.4 sphinx-rtd-theme<0.4 readthedocs-sphinx-ext<0.6 git+https://github.com/italia/docs-italia-theme@bootstrap-italia
cat conf.py
python /home/documents/user_builds/tre-civette-documento/envs/bozza/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=it . _build/html
python /home/documents/user_builds/tre-civette-documento/envs/bozza/bin/sphinx-build -T -b json -d _build/doctrees-json -D language=it . _build/json
python /home/documents/user_builds/tre-civette-documento/envs/bozza/bin/sphinx-build -T -b readthedocssinglehtmllocalmedia -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=it . _build/localmedia
python /home/documents/user_builds/tre-civette-documento/envs/bozza/bin/sphinx-build -b latex -D language=it -d _build/doctrees . _build/latex
pdflatex -interaction=nonstopmode /home/documents/user_builds/tre-civette-documento/checkouts/bozza/_build/latex/tre-civette-documento.tex
makeindex -s python.ist tre-civette-documento.idx
pdflatex -interaction=nonstopmode /home/documents/user_builds/tre-civette-documento/checkouts/bozza/_build/latex/tre-civette-documento.tex
mv -f /home/documents/user_builds/tre-civette-documento/checkouts/bozza/_build/latex/tre-civette-documento.pdf /home/documents/user_builds/tre-civette-documento/artifacts/bozza/sphinx_pdf/tre-civette-documento.pdf
python /home/documents/user_builds/tre-civette-documento/envs/bozza/bin/sphinx-build -T -b epub -d _build/doctrees-epub -D language=it . _build/epub
mv -f /home/documents/user_builds/tre-civette-documento/checkouts/bozza/_build/epub/Titolodeldocumento.epub /home/documents/user_builds/tre-civette-documento/artifacts/bozza/sphinx_epub/tre-civette-documento.epub
```

**Comment by pauloxnet** [comment]
Ho verificato che attualmente non è possibile creare un progetto che utilizzi markdown senza la presenza del file conf.py o di altri interventi al codice da verificare in una issue differente.

Ho creato un repository di documento base creato partendo dallo starter kit per pubblicare su Docs Italia e convertito in markdown.
https://github.com/comune-di-tre-civette-sul-como/tre-civette-markdown

Dopo l'import del repository in locale la build non si è conclusa con successo:
```bash
Build #2421
bozza (5fbe9dd9343a48dc69c8d25ad9a57c4e9cbdc78f)
Build failed
git clone --recursive https://github.com/comune-di-tre-civette-sul-como/tre-civette-markdown.git .
git checkout --force origin/master
git clean -d -f -f
git show-ref --tags
git branch -r
python2.7 -mvirtualenv --no-site-packages --no-download /home/documents/user_builds/tre-civette-markdown/envs/bozza
python /home/documents/user_builds/tre-civette-markdown/envs/bozza/bin/pip install --upgrade --cache-dir /home/documents/user_builds/tre-civette-markdown/.cache/pip Pygments==2.2.0 setuptools<40 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.7.4 sphinx-rtd-theme<0.4 readthedocs-sphinx-ext<0.6 git+https://github.com/italia/docs-italia-theme@bootstrap-italia
cat conf.py
python /home/documents/user_builds/tre-civette-markdown/envs/bozza/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=it . _build/html
Running Sphinx v1.7.4
loading translations [it]... done
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
reading sources... [ 33%] index

Traceback (most recent call last):
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 338, in build_update
    'out of date' % len(to_build))
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 351, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 565, in update
    self._read_serial(docnames, self.app)
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 584, in _read_serial
    self.read_doc(docname, app)
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 659, in read_doc
    doctree = read_doc(self.app, self, self.doc2path(docname))
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/sphinx/io.py", line 294, in read_doc
    pub.publish()
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/sphinx/transforms/__init__.py", line 96, in apply_transforms
    Transformer.apply_transforms(self)
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/recommonmark/transform.py", line 325, in apply
    self.traverse(self.document)
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/recommonmark/transform.py", line 297, in traverse
    self.traverse(child)
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/recommonmark/transform.py", line 287, in traverse
    newnode = self.find_replace(c)
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/recommonmark/transform.py", line 265, in find_replace
    newnode = self.auto_toc_tree(node)
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/recommonmark/transform.py", line 145, in auto_toc_tree
    self.current_level)
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/recommonmark/states.py", line 50, in reset
    self.memo.inliner.init_customizations(document.settings)
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 470, in init_customizations
    if settings.character_level_inline_markup:
AttributeError: Values instance has no attribute 'character_level_inline_markup'

Exception occurred:
  File "/home/documents/user_builds/tre-civette-markdown/envs/bozza/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 470, in init_customizations
    if settings.character_level_inline_markup:
AttributeError: Values instance has no attribute 'character_level_inline_markup'
The full traceback has been saved in /tmp/sphinx-err-YSz1Sz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Command time: 1s Return: 2
```

**Comment by yakky** [comment]
@francescozaia @pauloxnet la lasciamo aperte la rinominiamo esplicitando il fatto che il problema riguarda solo markdown o se ne apre un'altra specifica sul markdown per sistemare tutti eventuali problemi collegati al markdown?

**Comment by francescozaia** [comment]
Possiamo chiudere questa (grazie!), visto che abbiamo verificato che senza conf.py (e con `.rst`) è tutto ok. Andremo a creare un'altra story per capire come gestire anche `.md` nel modo più semplice possibile.
Tip per la discussione: nel backoffice di ~Docs Italia~ ReadTheDocs c'è già un menu a tendina a riguardo, che sicuramente fa qualcosa:
<img width="609" alt="Screenshot 2019-09-20 at 08 35 59" src="https://user-images.githubusercontent.com/481084/65304779-c42c1c00-db81-11e9-826f-3f21650c0cfb.png">

**Comment by yakky** [comment]
@francescozaia :+1:  chiudo allora
